version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - .:/app/
    restart: "on-failure"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python -Xfrozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:11-alpine
    volumes:
      - ~/pgsql/quiz_bot:/var/lib/postgresql/data/

    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGPORT=5432
      - POSTGRES_USER=postgres

    restart: "on-failure"

 # Redis
  redis:
    image: redis
    hostname: redis

